name: HexoBlogBuild
on:
  - workflow_dispatch
  - push
jobs:
  buildstatic:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.TOKEN }}
          publish_dir: ./
          external_repository: Fgaoxing/xyh-website
          publish_branch: main
          exclude_assets: ''
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
